name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.101
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: dotnet build --configuration Release /WarnAsError
