name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-22.04
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.101
      - name: Start PostgreSQL server
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create PostgreSQL role
        run: sudo -u postgres psql --command="CREATE USER buttercup_dev PASSWORD 'buttercup_dev' CREATEDB"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore .NET tools
        run: dotnet tool restore
      - name: Build application
        run: dotnet build --configuration Release /WarnAsError
      - name: Build database
        run: dotnet ef database update -s ./Buttercup.Api
      - name: Run tests
        run: dotnet test --no-build --configuration Release --collect "XPlat Code Coverage"
      - name: Report code coverage
        if: ${{ hashFiles('**/coverage.cobertura.xml') }}
        run: |
          dotnet reportgenerator \
            -reports:**/coverage.cobertura.xml \
            -assemblyfilters:-Buttercup.Api.DbModel.Migrations \
            -targetdir:CoverageReports \
            -reporttypes:TextSummary
          cat CoverageReports/Summary.txt
