name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-22.04
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.101
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore .NET tools
        run: dotnet tool restore
      - name: Build
        run: dotnet build --configuration Release /WarnAsError
      - name: Run tests
        run: dotnet test --no-build --configuration Release --collect "XPlat Code Coverage"
      - name: Report code coverage
        if: ${{ hashFiles('**/coverage.cobertura.xml') }}
        run: |
          dotnet reportgenerator -reports:**/coverage.cobertura.xml -targetdir:CoverageReports -reporttypes:TextSummary
          cat CoverageReports/Summary.txt
